### ISSUE TITLE
How to automatically start on Windows startup?

### ISSUE THREAD

**Issue by Mnaukal** [Phantom12/Unsplash-Wallpaper-Windows#1]
I really like your app, but I have noticed that it doesn't start automatically with Windows. I really miss this feature. Do you have a way to start is (ideally automatically minimized to system tray)?

**Comment by Phantom12** [comment]
Thanks Mnaukal. I have been setting the app to auto-start "At log on" using the Windows Task Scheduler (if you need an easy tutorial, http://www.sevenforums.com/tutorials/67503-task-create-run-program-startup-log.html).  I didn't automatically minimize the program as it didn't remember user's setting from previous run. I'm a bit busy this week. I will try and implement the features you suggest in a more elegant way by next week.

**Comment by Mnaukal** [comment]
Hello, any progress here? :)

**Comment by Phantom12** [comment]
Hi Michal,
Really sorry but I went out of town for the past two weeks. Will definitely
look at it this week.

Regards,
Wei

**Comment by Phantom12** [comment]
Hi Michal,
I just pushed an update which implements auto-start and also auto-save user's setting preferences. I did a quick test on my two PCs. Let me if there is any problem or other features you would like to see. Again, really sorry for the delay!

**Comment by Mnaukal** [comment]
Hi Wei,
you don't have to apologize for anything.
Just tested it on my PC and it works fine. One last thing: is it possible to start it hidden (so I wouldn't have to click *HIDE* everytime I boot my PC) ?
Thanks for this.

**Comment by Phantom12** [comment]
Just updated the latest version and here you go. https://github.com/Phantom12/Unsplash-Wallpaper-Windows/releases/download/2.3/Release.zip

**Comment by Mnaukal** [comment]
Awesome, thank you very much.
