### ISSUE TITLE
IDP.ALEXA.51 virus

### ISSUE THREAD

**Issue by Mnaukal** [Phantom12/Unsplash-Wallpaper-Windows#2]
Avast Antivirus is reporting this app as a virus (IDP.ALEXA.51).

**Comment by Phantom12** [comment]
Hi Mnaukal, sorry for the really late reply. I believe that was a false positive. I did a quick google on IDP.ALEXA.51: "The file detected may do various dangerous or unhealthy to the PC activities but may also be a false positive." (https://sensorstechforum.com/what-is-idp-alexa-51-and-should-you-remove-it/)

I uploaded the "Unsplash_GUI.exe" to virustotal (SHA-256: d8a230f1d9e2f1a89c63152cf143869ee5ec6a12e5a01f4a318e9538b113c5c3) and it seemed now none of the AV software flagged it virus, including Avast.

Also, I pushed a new update today, which allows the user to specify image category. I preemptively uploaded it to virustotal for scan as well, and the results were safe.
