### ISSUE TITLE
Save paticular wallpaper when using multiple monitors

### ISSUE THREAD

**Issue by NewbieToEverything** [Phantom12/Unsplash-Wallpaper-Windows#3]
Thank you for this useful tool! I am using your software with a dual-monitor setup and hope the current using wallpaper for a particular monitor could be saved respectively. For the current version, only the latest refreshed one, no matter which monitor it lies in, will be saved by using the hotkey.

**Comment by Phantom12** [comment]
Thank you for your support! I also thought about this feature myself a while ago, though I wasn't sure how to determine which monitor to save. I did not want to simply set different hotkeys as some people may choose to have a setup of three or even more monitors. Maybe it could be determined based on where the cursor is located when the user presses the hotkey? I'm a bit busy lately. I will have a look into it when I have some more time.

**Comment by NewbieToEverything** [comment]
Thank you for the quick reply! Using cursor as the indicator sounds a good idea. Hope it won't be a tricky feature to integrate into the existing structure. 

If you don't mind, I would like to ask for another feature. Is it possible to **hide** the setting window when click the top-right **close button** rather than exit the software, which is the case for now? I guess I was just so used to the way that other software did with the close button. I just want to close the setting window and keep your tools running when click the button. When I want to actually quit (I believe it would be very rare), I could turn to the tray and exit the software there.

**Comment by Phantom12** [comment]
I agree closing button to hide the window seems the more natural way software operates these days. I was also just learning Qt when I developed this project, and it was easier to just implement another button ("Hide" in the current version) to minimize the window. I will also have a go at that.

**Comment by NewbieToEverything** [comment]
Awesome! I will close this issue. Thank you again for your kind reply.
