### ISSUE TITLE
Is there a way to automate a new wallpaper by integrating this with AutoHotKey?

### ISSUE THREAD

**Issue by harsharora08** [Phantom12/Unsplash-Wallpaper-Windows#6]
Is there a command line argument which we can pass by which the wallpaper changes? That way, a convenient shortcut key can be assigned to change the wallpaper.
Thanks a lot.

**Comment by Phantom12** [comment]
Hi @harsharora08, I integreated the keyboard shortcut into the porgam. You can press "Ctrl + Alt + N" for a manual refresh and "Ctrl + Alt + S" to save the current wallpaper. Sorry I mentioned it in the "About" tab but forgot to document it in the README.md file.

**Comment by harsharora08** [comment]
Oh, I just tried it and it works perfectly. Thanks a lot for this project. And also, if I customize the source URL within the config.ini, it doesn't work.
Am I doing something wrong here?

___________
Attachments.
![image](https://user-images.githubusercontent.com/41362690/125281455-dddcbb80-e333-11eb-9120-a5a7bddf8590.png)
![image](https://user-images.githubusercontent.com/41362690/125281425-d5848080-e333-11eb-8775-3ed67b604094.png)

**Comment by Phantom12** [comment]
Sorry but it's rather a limitation with my implementation. Searching with keyword is not supported at the moment, unfortunately. Basically, the program queries with {sourceURL}/{WIDTHxHEIGHT}. According to https://source.unsplash.com/, the syntax to search keywords is instead https://source.unsplash.com/{WIDTHxHEIGHT}/?{KEYWORD},{KEYWORD}.

**Comment by harsharora08** [comment]
Is this implementation subject to change in a future update because that would really help a lot in the cusomization of wallpapers. Other than that, this is a really great project.
Thank you.

**Comment by Phantom12** [comment]
Thank you. Sorry I haven't palnned for one in the near future. In the meantime, may I suggest setting the soureURL to a collection on the topic of interest as an alternative to keyword search? The syntax is https://source.unsplash.com/collection/{COLLECTION ID}.

**Comment by harsharora08** [comment]
Alright, thank you for the support. Have a great day!

**Comment by harsharora08** [comment]
Hello, once again. I tried what you said using collection ID, but this is not working. Is this how I should do it?
![image](https://user-images.githubusercontent.com/41362690/125796256-63244be2-7b37-4ab0-b0e4-3af26920a868.png)
